image: php:7.0
#image: magento/magento2devbox-web

cache:
  paths:
  - vendor/
  

before_script:
  - apt-get update -yqq
  #- apt-get install -yqq git libmcrypt-dev libpq-dev libcurl4-gnutls-dev libicu-dev libvpx-dev libjpeg-dev libpng-dev libxpm-dev zlib1g-dev libfreetype6-dev libxml2-dev libexpat1-dev libbz2-dev libgmp3-dev libldap2-dev unixodbc-dev libsqlite3-dev libaspell-dev libsnmp-dev libpcre3-dev libtidy-dev libxslt libxslt1-dev
  - apt-get install -yqq apt-utils sudo wget unzip cron curl libmcrypt-dev libicu-dev libxml2-dev libxslt1-dev libfreetype6-dev libjpeg62-turbo-dev libpng12-dev git vim openssh-server supervisor
  # Install PHP extensions
  - docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
  - docker-php-ext-configure hash --with-mhash
  #- docker-php-ext-install mbstring mcrypt pdo_pgsql curl json intl gd xml zip bz2 opcache xsl
  - docker-php-ext-install mcrypt intl xsl gd zip pdo_mysql opcache soap bcmath json iconv
  # Install & enable Xdebug for code coverage reports
  #- pecl install xdebug
  #- docker-php-ext-enable xdebug
  # Install and run Composer
  - curl -sS https://getcomposer.org/installer | php
  - echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${COMPOSER_MAGENTO_USERNAME}\",\"password\":\"${COMPOSER_MAGENTO_PASSWORD}\"}}}" > auth.json
  - php composer.phar install

stages:
  - build

build:
  stage: build
  script:
    #- vendor/bin/phpunit --configuration phpunit.xml --coverage-text --colors=never
    - php vendor/bin/phpcbf --runtime-set installed_paths vendor/magento/marketplace-eqp --runtime-set ignore_warnings_on_exit 1 --standard=MEQP2 src
    - php vendor/bin/phpcs --runtime-set installed_paths vendor/magento/marketplace-eqp --runtime-set ignore_warnings_on_exit 1 --standard=MEQP2 src
    #- php vendor/bin/phpmd src/Block/,Helper/,Model/,Observer/,Setup/ text cleancode,codesize,controversial,design,naming,unusedcode
    #- php vendor/bin/phpcpd Block/ Helper/ Model/ Observer/ Setup/
    #- php vendor/bin/phpunit --coverage-clover build/logs/clover.xml
